### ISSUE TITLE
Static Tokenization

### ISSUE THREAD

**Issue by richardblythman** [tahmid0007/VisualTransformers#1]
Hi,

It doesn't seem like you implement the tokenization step (section 3.1.1 of the paper). Do you have plans to add this?

Thanks.

**Comment by tahmid0007** [comment]
Hi Richard,

I looked into it and implemented the tokenization step as per section 3.1.1 of the paper. Have a look here
https://github.com/tahmid0007/VisualTransformers/blob/fc2287c842704b0f0e22fc778580ca84c67d8221/ResViT.py#L170
Let me know if you have any further issues. 

Thanks

**Comment by richardblythman** [comment]
Hi Tahmid, thanks for looking into it and working on an implementation. There are still quite a few key parts missing from the original paper. Have a look at the sections on dynamic tokenization and projection. Also, your transformer architecture is different. Check out the pseudo code in the appendix. You're currently the only code implementation of the paper on Papers with Code so the pressure's on :D

**Comment by tahmid0007** [comment]
Hi Richard,

Thanks for pointing out. I was aware of some of the differences with the pseudocode but what I have observed from experience is that most of these do not impact the performance much. However, I will keep a note of the major ones and update accordingly. 

So far the pressures just been from you :D , cheers mate 👍
