### ISSUE TITLE
Semantic Segmentation

### ISSUE THREAD

**Issue by Doubiiu** [tahmid0007/VisualTransformers#3]
Hi. Thanks for your works! Is it possible for you to give an alternative version of semantic segmentation? I see your version is on classification. Thanks!

**Comment by tahmid0007** [comment]
Hi there,
Thanks for your interest. I believe you are interested in detection/segmentation line of work and suggest you have a look here [DETR](https://github.com/tahmid0007/DETR_FineTune). As you might know, DETR is quite popular in those sort of tasks and employs the exact same attention techniques as in Visual Transformers.
