### ISSUE TITLE
No Documentation!

### ISSUE THREAD

**Issue by DebanganThakuria** [tahmid0007/VisualTransformers#5]
...a little documentation will be appreciated.

I am especially having a hard time understanding the parameters of the main VitResNet Class.

**Comment by tahmid0007** [comment]
Hi Debangan,

I appreciate your interest in the work. While I understand your request for further clarity, one should know that the transformer networks have a number of bells and whistles. This repo has a number of comments inside the code but presumes the reader has already gone through the paper. Understanding the paper is highly recommended. nevertheless, I will try in future to incorporate documentation.

**Comment by DebanganThakuria** [comment]
Thanks for the reply, Tahmid.

I am trying to use your work (I have read the Original Paper) in my project. But, I am getting many errors. Here I should admit that I am very new to PyTorch and don't get the nitty-gritty of this difficult-to-understand framework. 
So, my images are of dim 50 x 50 x 3 and have 2 classes(pos and neg). Which parameters should I modify to use the VitResNet in my work? A little help from you, the author of this code, will be highly appreciated.

**Comment by tahmid0007** [comment]
def __init__(self, block, num_blocks, num_classes=10, dim = 128, num_tokens = 8, mlp_dim = 256, heads = 8, depth = 6, emb_dropout = 0.1, dropout= 0.1):
For your case, num_classes is 2 (pos,neg). Just so you have better clarity, the first segment of the code is a vanilla resnet and a transformer takes over from an intermediate layer (16x16).
Share screenshots of your errors in the future.
Thanks
