### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zhenglongjiepheonix** [tahmid0007/VisualTransformers#6]
Hello, it seems that your implementation is different from the original paper, there are some modifications in transformer layer in original paper while you simply use original transformer here. And I think according to the original paper, the transformer layer is just one layer which is single-headed(simply T_in and T_out) and thus there are no paramters specializing(number of heads, depth of transformer,etc)

**Comment by tahmid0007** [comment]
Hi there,
Thanks for your interest in the work. First of all, I have to cross-check the differences but be assured that the performance does remain almost same with 1, 8 or even more than 8 attention heads. Same thing happens with the number of layers as well, doesn't really impact the ultimate outcome. If you explore more, you will find that these hyperparameters are taken casually most of the times. Nevertheless, I will update relevant parts if deemed necessary.
Thanks

**Comment by zhenglongjiepheonix** [comment]
I see, thanks for reply

**Comment by zhenglongjiepheonix** [comment]
by the way, do you know the difference between feature Map channel and visual token channel, I mean, they are both denoted by C in the paper and they seems to be the same according to the matrix multiplication, thanks for reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tahmid0007/VisualTransformers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 上午7:27
收件人:&nbsp;"tahmid0007/VisualTransformers"<VisualTransformers@noreply.github.com&gt;;
抄送:&nbsp;"Phoenix"<1603126421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tahmid0007/VisualTransformers] some questions (#6)





 
Hi there,
 Thanks for your interest in the work. First of all, I have to cross-check the differences but be assured that the performance does remain almost same with 1, 8 or even more than 8 attention heads. Same thing happens with the number of layers as well, doesn't really impact the ultimate outcome. If you explore more, you will find that these hyperparameters are taken casually most of the times. Nevertheless, I will update relevant parts if deemed necessary.
 Thanks

**Comment by tahmid0007** [comment]
If you look closely, you will see that they referred the feature map dimension as HWxC, here C is simply the number of filters. but for tokens, they refer it as LxC, where C is the width of each token. You can think of it like, each token has 1 participant from each of the C feature maps and each token has C length. I hope that makes your concept clear.

**Comment by zhenglongjiepheonix** [comment]
Yeah I mean. according to formula T = softmax_{HW}(XW_A)^T X , where X \in R^{HW,C}, here C is feature map dimension, according to the matrix multiplication rule, T must has the same last dimension C, and T here should be tokens, which means C in tokens and C in X,&nbsp; are the same?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tahmid0007/VisualTransformers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午2:35
收件人:&nbsp;"tahmid0007/VisualTransformers"<VisualTransformers@noreply.github.com&gt;;
抄送:&nbsp;"Phoenix"<1603126421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tahmid0007/VisualTransformers] some questions (#6)





 
If you look closely, you will see that they referred the feature map dimension as HWxC, here C is simply the number of filters. but for tokens, they refer it as LxC, where C is the width of each token. You can think of it like, each token has 1 participant from each of the C feature maps and has each token has C length. I hope that makes your concept clear.

**Comment by zhenglongjiepheonix** [comment]
Hi again, I have contacted the author and he says I can use an additional matrix multiplication to change the dimension of tokens




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tahmid0007/VisualTransformers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午2:35
收件人:&nbsp;"tahmid0007/VisualTransformers"<VisualTransformers@noreply.github.com&gt;;
抄送:&nbsp;"Phoenix"<1603126421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tahmid0007/VisualTransformers] some questions (#6)





 
If you look closely, you will see that they referred the feature map dimension as HWxC, here C is simply the number of filters. but for tokens, they refer it as LxC, where C is the width of each token. You can think of it like, each token has 1 participant from each of the C feature maps and has each token has C length. I hope that makes your concept clear.
